import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** 读取小型纯文本 */
function readText(rootDir, filename) {
  const filePath = path.resolve(rootDir, filename);
  return fs.readFileSync(filePath, { encoding: 'utf-8'});
}

const prefix = path.resolve(__dirname, './src/ui-client/consolidated/summary/process-data/items');

// 统计项目名称
const processItemsMap = {
  property: readText(prefix, './property.txt').split(/\n/).map(it => it.trimEnd()),
  debtEquity: readText(prefix, './debtEquity.txt').split(/\n/).map(it => it.trimEnd()),
  profit: readText(prefix, './profit.txt').split(/\n/).map(it => it.trimEnd()),
  cashFlow: readText(prefix, './cashFlow.txt').split(/\n/).map(it => it.trimEnd()),
};

fs.writeFileSync(path.resolve(prefix, './index.ts'), `// This file is generated by preprocess.mjs, run \`npm run preprocess\` to generate it automatically instead of manually modified!\nexport default ${JSON.stringify(processItemsMap, null, 2)}`, 'utf-8');

console.log('preprocess done!!!');